// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Mirrors Next.js's own env precedence (.env then .env.local override) so
// the Prisma CLI and the app agree on which database they're pointed at.
import { config } from "dotenv";
config({ path: ".env" });
config({ path: ".env.local", override: true });

import { defineConfig, env } from "prisma/config";

// Only used by `prisma migrate dev` to diff schema changes locally. On Vercel
// the variable is either unset or saved as an empty string, and `migrate
// deploy` rejects an explicit "" with P1013 ("must not be an empty string"),
// so the key has to be left out entirely unless there's a real value.
const shadowDatabaseUrl = process.env.SHADOW_DATABASE_URL?.trim() || undefined;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
    ...(shadowDatabaseUrl ? { shadowDatabaseUrl } : {}),
  },
});
